In [17]:
import pandas as pd
import datetime as date

In [18]:
btc_d = pd.read_csv(r'Data\BTC\BTC_D.csv')

In [11]:
pd.read_csv(r'Data\BTC\BTC_D.csv')

,time,open,high,low,close,Volume,Volume MA,Volume.1,Volume MA.1,RSI,...,OnBalanceVolume.1,ADX,Aroon Up,Aroon Down,Histogram,MACD,Signal,RSI.1,%K,%D
0,1434844800,246.08,246.98,242.00,244.66,3632.000000,6051.800000,3632.000000,6051.800000,61.352773,...,2.304900e+04,26.387053,71.428571,0.000000,1.834624,3.822229,1.987605,61.352773,58.693832,62.119741
1,1434931200,244.66,248.50,243.86,247.50,5543.000000,5882.050000,5543.000000,5882.050000,64.552308,...,2.859200e+04,26.865542,64.285714,0.000000,1.626906,4.021238,2.394332,64.552308,62.007624,61.420259
2,1435017600,247.48,248.06,243.01,244.52,5264.000000,5803.850000,5264.000000,5803.850000,59.029962,...,2.332800e+04,27.077561,57.142857,7.142857,1.199422,3.893609,2.694187,59.029962,52.541296,57.747584
3,1435104000,244.54,244.92,239.51,240.04,5281.000000,5771.750000,5281.000000,5771.750000,51.848767,...,1.804700e+04,26.367777,50.000000,0.000000,0.558142,3.391865,2.833723,51.848767,36.866060,50.471660
4,1435190400,240.14,243.44,239.91,242.44,5637.000000,5724.600000,5637.000000,5724.600000,55.006612,...,2.368400e+04,25.708693,42.857143,0.000000,0.254270,3.151560,2.897290,55.006612,44.506032,44.637796
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2319,1635206400,63081.96,63290.49,59837.07,60337.62,12046.433399,13891.671260,12046.433399,13891.671260,56.944475,...,1.939692e+06,40.847915,57.142857,0.000000,-397.232251,3202.081402,3599.313653,56.944475,47.806731,56.807205
2320,1635292800,60333.19,61488.00,58100.00,58455.47,18714.237237,14037.927322,18714.237237,14037.927322,52.285476,...,1.920977e+06,39.362018,50.000000,0.000000,-658.077679,2776.716554,3434.794233,52.285476,15.965389,44.550981
2321,1635379200,58462.73,62477.47,57653.88,60591.65,18592.151615,14352.773732,18592.151615,14352.773732,56.623245,...,1.939570e+06,38.302648,42.857143,0.000000,-682.061367,2582.217524,3264.278892,56.623245,36.760565,33.510895
2322,1635465600,60591.63,62974.00,60188.73,62276.72,15445.295737,14772.637267,15445.295737,14772.637267,59.733024,...,1.955015e+06,37.477569,35.714286,0.000000,-583.561671,2534.826803,3118.388474,59.733024,49.467958,34.064637
2323,1635552000,62287.95,62379.20,60763.25,61279.47,4751.636541,14543.823761,4751.636541,14543.823761,57.111407,...,1.950263e+06,36.711425,28.571429,85.714286,-583.598820,2388.889949,2972.488769,57.111407,38.747282,41.658602

In [15]:
btc_d.apply()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2324 entries, 0 to 2323
Data columns (total 23 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   time                         2324 non-null   int64
 1   open                         2324 non-null   float64
 2   high                         2324 non-null   float64
 3   low                          2324 non-null   float64
 4   close                        2324 non-null   float64
 5   Volume                       2324 non-null   float64
 6   Volume MA                    2324 non-null   float64
 7   Volume.1                     2324 non-null   float64
 8   Volume MA.1                  2324 non-null   float64
 9   RSI                          2324 non-null   float64
 10  OnBalanceVolume              2324 non-null   float64
 11  Accumulation/Distribution    2324 non-null   float64
 12  Accumulation/Distribution.1  2324 non-null   float64
 13  OnBalanceVolume.1            2324 non-null   float64
 14  ADX                          2324 non-null   float64
 15  Aroon Up                     2324 non-null   float64
 16  Aroon Down                   2324 non-null   float64
 17  Histogram                    2324 non-null   float64
 18  MACD                         2324 non-null   float64
 19  Signal                       2324 non-null   float64
 20  RSI.1                        2324 non-null   float64
 21  %K                           2324 non-null   float64
 22  %D                           2324 non-null   float64
dtypes: float64(22), int64(1)
memory usage: 417.7 KB